---
- name: Create EC2 Instance
  hosts: localhost
  tasks:
    - ec2:
        key_name: vbk
        instance_type: t2.micro
        image: ami-0d5d9d301c853a04a
        wait: yes
        group:  Ubuntu
        count: 2
        vpc_subnet_id: subnet-f41d528e
        assign_public_ip: yes
        region: us-east-2
      register: out

    - debug:
        msg: "{{out}}"
